#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-Math-Derivative
Version  : 1.01
Release  : 1
URL      : https://cpan.metacpan.org/authors/id/J/JG/JGAMBLE/Math-Derivative-1.01.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/J/JG/JGAMBLE/Math-Derivative-1.01.tar.gz
Source1  : http://http.debian.net/debian/pool/main/libm/libmath-derivative-perl/libmath-derivative-perl_1.01-1.debian.tar.xz
Summary  : 'Numeric 1st and 2nd order differentiation.'
Group    : Development/Tools
License  : Artistic-1.0 Artistic-1.0-Perl GPL-1.0
Requires: perl-Math-Derivative-license
Requires: perl-Math-Derivative-man
Requires: perl(Math::Utils)
BuildRequires : perl(Math::Utils)

%description
Math-Derivative, version 1.01, 9 August 2017
Numeric 1st and 2nd order differentiation.

%package license
Summary: license components for the perl-Math-Derivative package.
Group: Default

%description license
license components for the perl-Math-Derivative package.


%package man
Summary: man components for the perl-Math-Derivative package.
Group: Default

%description man
man components for the perl-Math-Derivative package.


%prep
tar -xf %{SOURCE1}
cd ..
%setup -q -n Math-Derivative-1.01
mkdir -p %{_topdir}/BUILD/Math-Derivative-1.01/deblicense/
mv %{_topdir}/BUILD/debian/* %{_topdir}/BUILD/Math-Derivative-1.01/deblicense/

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/perl-Math-Derivative
cp LICENSE %{buildroot}/usr/share/doc/perl-Math-Derivative/LICENSE
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot}
else
./Build install --installdirs=site --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)
/usr/lib/perl5/site_perl/5.26.1/Math/Derivative.pm

%files license
%defattr(-,root,root,-)
/usr/share/doc/perl-Math-Derivative/LICENSE

%files man
%defattr(-,root,root,-)
/usr/share/man/man3/Math::Derivative.3
